### Crear un Cliente
POST http://localhost:10000/clientes HTTP/1.1
Content-Type: application/json

{
    "cedula": "1112628968",
    "nombre": "Yonathan",
    "email": "Ynathan.cjimenezristina@example.com"
}


### Eliminar un cliente
DELETE http://localhost:10000/clientes/671d01a0d4514563094d76f7 HTTP/1.1
Content-Type: application/json


### Actualizar un cliente
PUT http://localhost:10000/clientes/671d03a0d5e7a0b443d04ab6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Yonathan jimenez Actualizado",
    "email": "Yonathan.Jimenez.actualizado@example.com"
}


### Mostrar todos los clientes
GET http://localhost:10000/clientes HTTP/1.1



### Mostrar los productos de un cliente
GET http://localhost:10000/clientes/671d03a0d5e7a0b443d04ab6/productos



################__________________________________________________________##################################


POST http://localhost:10000/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Producto 2",
    "precio": 20,
    "clienteId": "671d03a0d5e7a0b443d04ab6"
}
